import { ROTATE_SVG, ROTATE_SVG_ACTIVE, ROTATE_CURSOR, COPY_SVG, COPY_SVG_ACTIVE, DEL_SVG, DEL_SVG_ACTIVE, DRAW_MODE_CURSOR, DRAG_ICON, CLEAR_ICON, LOGO_ICON } from './path'

export default { ROTATE_SVG, ROTATE_SVG_ACTIVE, ROTATE_CURSOR, COPY_SVG, COPY_SVG_ACTIVE, DEL_SVG, DEL_SVG_ACTIVE, DRAW_MODE_CURSOR, DRAG_ICON, CLEAR_ICON, LOGO_ICON }